credentials hidden
chirozie/ETL-Pipeline pull request #1
Opened 2024-04-07 17:52 UTC by GadAugust

The only change made was to hide the credentials. not been able to connect to click house.

2024-04-08 09:24 UTC, chirozie commented on main.py
> +from load import load_csv_to_postgrest
you have a typo here. the postgrest instead of postgres

2024-04-08 09:25 UTC, chirozie commented on main.py
> +   # load_csv_to_postgres('tripdata.csv', 'tripdata')
you have commented out the load_csv_to_postgres function. while i understand why you did this, it was for your testing. the code to be merged to the main branch should not have this line commented out.

2024-04-08 09:27 UTC, chirozie requested changes
Check my comments and resolve them. then commit and push again.

2024-04-11 19:44 UTC, GadAugust commented on main.py
> +from load import load_csv_to_postgrest
Thank you
resolved.

2024-04-11 19:45 UTC, GadAugust commented on main.py
> +   # load_csv_to_postgres('tripdata.csv', 'tripdata')
Thank you resolved.

2024-04-11 19:46 UTC, closed without merging